title: This is my GitHub site!
author: willcuratolo
email: willcuratolo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my test GitHub site!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
